"""initial config schema

Revision ID: 2ddb5bd4a7d7
Revises: 
Create Date: 2025-07-15 14:50:52.066217

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2ddb5bd4a7d7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_columns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dtype", sa.String(length=20), nullable=False),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        schema="config",
    )
    with op.batch_alter_table("base_columns", schema="config") as batch_op:
        batch_op.create_index(batch_op.f("ix_config_base_columns_order"), ["order"], unique=True)

    op.create_table(
        "customer_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("konserni", sa.JSON(), nullable=False),
        sa.Column("source_container", sa.String(length=100), nullable=False),
        sa.Column("destination_container", sa.String(length=100), nullable=False),
        sa.Column("file_format", sa.String(length=50), nullable=False),
        sa.Column("file_encoding", sa.String(length=50), nullable=False),
        sa.Column("extra_columns", sa.JSON(), nullable=True),
        sa.Column("exclude_columns", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="config",
    )
    op.create_table(
        "general_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("retry_attempts", sa.Integer(), nullable=False),
        sa.Column("retry_delay", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="config",
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("settings_id", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["settings_id"], ["config.general_settings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="config",
    )
    op.drop_table("alembic_version")
    op.drop_table("test", schema="esrs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column(
            "Id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "TapahtumaId",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "Konserninumero",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Tyhjennyskohde",
            sa.VARCHAR(length=1050, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Osoite",
            sa.VARCHAR(length=1050, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Viite",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Maksaja",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Asiakasryhma",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Asiakasnro",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Hinta", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column(
            "Energiahyotyaste",
            sa.NUMERIC(precision=16, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "EWCkoodi",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "VopKoodi",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Vastaanottopaikka",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Jkmaksu", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column(
            "Materiaalihyotyaste",
            sa.NUMERIC(precision=16, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Kello",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Maara", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True),
        sa.Column(
            "Nimike",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Kasittelytapa",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Paino", sa.NUMERIC(precision=16, scale=3), autoincrement=False, nullable=True),
        sa.Column(
            "Pvm",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Tyyppi",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Yhteensa", sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=True
        ),
        sa.Column(
            "Tuoteryhma",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("Id", "TapahtumaId", name=op.f("PK__test__48C41A084D9577E8")),
        schema="esrs",
    )
    op.create_table(
        "alembic_version",
        sa.Column(
            "version_num",
            sa.VARCHAR(length=32, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
    )
    op.drop_table("emails", schema="config")
    op.drop_table("general_settings", schema="config")
    op.drop_table("customer_configs", schema="config")
    with op.batch_alter_table("base_columns", schema="config") as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_base_columns_order"))

    op.drop_table("base_columns", schema="config")
    # ### end Alembic commands ###
