"""initial

Revision ID: 811bc7bdad71
Revises: 
Create Date: 2025-07-15 14:28:26.300838

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "811bc7bdad71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("base_columns")
    op.drop_table("emails")
    op.drop_table("customer_configs")
    op.drop_table("general_settings")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "general_settings",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("retry_attempts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("retry_delay", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="PK__general___3213E83FD93A2494"),
    )
    op.create_table(
        "customer_configs",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "konserni",
            sa.NVARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "source_container",
            sa.VARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "destination_container",
            sa.VARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "file_format",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "file_encoding",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "extra_columns",
            sa.NVARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "exclude_columns",
            sa.NVARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("enabled", mssql.BIT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK__customer__3213E83F88627FDE")),
    )
    op.create_table(
        "emails",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("settings_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "address",
            sa.NVARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.VARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["general_settings.id"],
            name=op.f("FK__emails__settings__5629CD9C"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("PK__emails__3213E83FFCF1F297")),
    )
    op.create_table(
        "base_columns",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=False, start=1, increment=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "key",
            sa.VARCHAR(length=100, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=255, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "dtype",
            sa.VARCHAR(length=20, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("length", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("decimals", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("PK__base_col__3213E83FB10C09F8")),
    )
    # ### end Alembic commands ###
